//
//  platform_types.h
//  xe
//
//  Created by admin on 11/20/21.
//

#ifndef platform_types_h
#define platform_types_h

// STRUCT proc
#define TYPE_PROC_MEM_P_LIST_OFFSET 0
#define TYPE_PROC_MEM_P_PID_OFFSET  104
#define TYPE_PROC_MEM_P_UTHLIST_OFFSET 152
#define TYPE_PROC_MEM_P_FD_OFFSET   224

// STRUCT uthread
#define TYPE_UTHREAD_MEM_SYSCALL_CODE_OFFSET 74
#define TYPE_UTHREAD_MEM_UU_LIST_OFFSET 296
#define TYPE_UTHREAD_MEM_UU_THREAD_OFFSET 224

// STRUCT thread
#define TYPE_THREAD_MEM_STATE_OFFSET 456
#define TYPE_THREAD_MEM_KERNEL_STACK_OFFSET 232

// STRUCT filedesc
#define TYPE_FILEDESC_MEM_FD_NFILES_OFFSET 20
#define TYPE_FILEDESC_MEM_FD_OFILES_OFFSET 32

// STRUCT fileproc
#define TYPE_FILEPROC_MEM_FP_GLOB_OFFSET 16

// STRUCT fileglob
#define TYPE_FILEGLOB_MEM_FG_DATA_OFFSET 56

// STRUCT socket
#define TYPE_SOCKET_MEM_SO_PCB_OFFSET 16
#define TYPE_SOCKET_MEM_SO_PROTO_OFFSET 24

// STRUCT inpcb
#define TYPE_INPCB_MEM_INPCB_MTX_OFFSET 0

// STRUCT protosw
#define TYPE_PROTOSW_SIZE 168
#define TYPE_PROTOSW_MEM_PR_DOMAIN_OFFSET 16
#define TYPE_PROTOSW_MEM_PR_LOCK_OFFSET 104
#define TYPE_PROTOSW_MEM_PR_UNLOCK_OFFSET 112
#define TYPE_PROTOSW_MEM_PR_GETLOCK_OFFSET 120

// STRUCT domain
#define TYPE_DOMAIN_SIZE 136
#define TYPE_DOMAIN_MEM_DOM_MTX_OFFSET 16

// STRUCT pipe
#define TYPE_PIPE_MEM_PIPE_BUFFER_OFFSET 0

// STRUCT pipebuf
#define TYPE_PIPEBUF_MEM_SIZE_OFFSET 12
#define TYPE_PIPEBUF_MEM_BUFFER_OFFSET 16

// STRUCT kalloc_heap
#define TYPE_KALLOC_HEAP_MEM_KH_LARGE_MAP_OFFSET 40

// STRUCT vm_map
#define TYPE_VM_MAP_MEM_LCK_RW_OFFSET 0

// STRUCT msdosfsmount
#define TYPE_MSDOSFSMOUNT_SIZE 344
#define TYPE_MSDOSFSMOUNT_MEM_PM_MOUNTP_OFFSET 0
#define TYPE_MSDOSFSMOUNT_MEM_PM_DEVVP_OFFSET 24
#define TYPE_MSDOSFSMOUNT_MEM_PM_BPB_OFFSET 32
#define TYPE_MSDOSFSMOUNT_MEM_PM_FAT_BLOCK_SIZE_OFFSET 108
#define TYPE_MSDOSFSMOUNT_MEM_PM_FAT_MASK_OFFSET 112
#define TYPE_MSDOSFSMOUNT_MEM_PM_FATMULT 132
#define TYPE_MSDOSFSMOUNT_MEM_PM_FLAGS_OFFSET 144
#define TYPE_MSDOSFSMOUNT_MEM_PM_LABEL_OFFSET 168
#define TYPE_MSDOSFSMOUNT_MEM_PM_FAT_ACTIVE_VP_OFFSET 256
#define TYPE_MSDOSFSMOUNT_MEM_PM_FAT_MIRROR_VP_OFFSET 264
#define TYPE_MSDOSFSMOUNT_MEM_PM_FAT_CACHE_OFFSET 280
#define TYPE_MSDOSFSMOUNT_MEM_PM_FAT_BYTES_OFFSET 288
#define TYPE_MSDOSFSMOUNT_MEM_PM_FAT_CACHE_OFFSET_OFFSET 292
#define TYPE_MSDOSFSMOUNT_MEM_PM_FAT_FLAGS_OFFSET 296
#define TYPE_MSDOSFSMOUNT_MEM_PM_SYNC_TIMER 312

// STRUCT bpb50
#define TYPE_BPB50_MEM_BPB_FATS_OFFSET 6

#endif /* platform_types_h */
